### ISSUE TITLE
Wifi Mac Address Not Randomized

### ISSUE THREAD

**Issue by ghost** [raphaelthegreat/device_nokia_NB1#4]
I'm not sure how to go about researching/fixing this but the Wifi mac address is never randomized. 

ROM: both ancient and lineage.  
Kernel: both lineage-18.1 and next

**Comment by radu-v** [comment]
not sure about this new dev tree, but previously we've discovered that hotspot wasn't accepting connections (on 5GHz at least) due to MAC randomization.
For the umod kernel, [this hack](https://github.com/radu-v/umbrella-mod/commit/83112b1d4c087a24ddaacef8a96ed1d957912950) fixed hotspot, but I think there was also a commit in the old tree that was disabling MAC randomization. It is enabled in this tree, though, as I see [here](https://github.com/GPUCode/device_nokia_NB1/blob/dot11/rro_overlays/WifiOverlay/res/values/config.xml) 🤔

**Comment by ghost** [comment]
I don't think that the old tree disabled MAC randomization.

When using the old tree, it was working fine on both the old kernel and umbrella mod

**Comment by raphaelthegreat** [comment]
Mac randomization has been enabled from the overlay with this commit: https://github.com/GPUCode/device_nokia_NB1/commit/6b1eba872f3e4756b143b0678f12022ca4b3937b
In past the only way to fix hotspot was to disable mac randomization. However I found this fix: https://github.com/GPUCode/device_nokia_NB1/commit/4c7eed4e3ffaab0f9a355724ed16f4607a30c631 that seems to make hotspot work with mac randomization enabled. I don't know why it doesn't work for you as it should be enabled. Some logs (boot/run) would be of great help.

**Comment by ghost** [comment]
@GPUCode I don't think I have problems with hotspot. My issue is that when connecting to a Wi-Fi network, the MAC address is not randomized. 

```
09-28 14:52:01.514  1372  1503 I EthernetTracker: interfaceLinkStateChanged, iface: wlan0, up: false
09-28 14:52:01.516   892   892 E android.hardware.wifi@1.0-service: Could not set interface MAC address for wlan0 (Device or resource busy)
09-28 14:52:01.516   892   892 E android.hardware.wifi@1.0-service: SetMacAddress failed.
09-28 14:52:01.514  1372  1503 I chatty  : uid=1000(system) android.fg identical 1 line
09-28 14:52:01.515  1372  1503 I EthernetTracker: interfaceLinkStateChanged, iface: wlan0, up: false
09-28 14:52:01.516  1372  2181 E WifiVendorHal: setMacAddress(l.1318) failed {.code = ERROR_UNKNOWN, .description = }
09-28 14:52:01.517  1372  2181 D WifiClientModeImpl: ConnectedMacRandomization SSID(qBDbg0K9eKaG8Gwkn1cLxUf9kqMslsaX). setMacAddress(16:21:25:9c:96:42) from 04:f1:28:6d:28:a2 = false
09-28 14:52:01.518   862  2948 I vendor.qti.bluetooth@1.0-ibs_handler: ProcessIbsCmd: Received IBS_SLEEP_IND: 0xFE
09-28 14:52:01.518  1372  2181 I WifiClientModeImpl: Connecting with 04:f1:28:6d:28:a2 as the mac address
09-28 14:52:01.519  1148  1148 W wificond: Scan is not started. Ignore abort request
```

**Comment by ghost** [comment]
Not sure if this helps but `p2p0`'s mac address gets randomized every time I reconnect to a Wi-Fi network but not `wlan0`.  

I'm under the impression that this might mean that Android might be thinking that `p2p0` is the Wi-Fi interface, however, considering the logs clearly state that Android is trying to change the MAC address of `wlan0` and not `p2p0`. Therefore, I guess this is a completely unrelated observation.

**Comment by ghost** [comment]
I think it is important to mention that I could change the mac address with `ip link set wlan0 address ...`. So the issue is probably with the ROM and not the kernel.

**Comment by raphaelthegreat** [comment]
> I think it is important to mention that I could change the mac address with `ip link set wlan0 address ...`. So the issue is probably with the ROM and not the kernel.

The patch that disabled mac randomization in the kernel has been reverted a along time ago, every since the ROM side patch was discovered.

**Comment by ghost** [comment]
@GPUCode Any idea or tips on why Android fails to change the mac address? MAC address randomization is important to me because it allows me to get unlimited free 30 min Wi-Fi and `ip link set...` is pretty inconvenient 

Edit: I've tried to search online but I can't find anything :/

**Comment by raphaelthegreat** [comment]
I have a few fixes in mind. Let me upload them to the device and you can test if they fix anything.

**Comment by raphaelthegreat** [comment]
Just pushed to the dot11 branch

**Comment by ghost** [comment]
I'm building it now, will let you know if it works or not!

Edit: I think I did something similar but not sure if I removed wpa_supplicant from init.qcom.rc.

**Comment by ghost** [comment]
Sadly no luck with your change  but it did not break anything

**Comment by ghost** [comment]
Removing `WIFI_AVOID_IFACE_RESET_MAC_CHANGE` fixes this issue.

```diff
c79@paranoid-lane:~/android/lineage/device/nokia/NB1$ git diff 
diff --git a/BoardConfig.mk b/BoardConfig.mk
index 12fb160..f23eb92 100644
--- a/BoardConfig.mk
+++ b/BoardConfig.mk
@@ -155,7 +155,6 @@ BOARD_HOSTAPD_PRIVATE_LIB := lib_driver_cmd_$(BOARD_WLAN_DEVICE)
 WIFI_DRIVER_FW_PATH_AP  := "ap"
 WIFI_DRIVER_FW_PATH_P2P := "p2p"
 WIFI_DRIVER_FW_PATH_STA := "sta"
-WIFI_AVOID_IFACE_RESET_MAC_CHANGE := true
 WIFI_HIDL_FEATURE_DUAL_INTERFACE := true
 WIFI_HIDL_UNIFIED_SUPPLICANT_SERVICE_RC_ENTRY := true
 WPA_SUPPLICANT_VERSION := VER_0_8_X
c79@paranoid-lane:~/android/lineage/device/nokia/NB1$ 
```

Edit: 

I think it is important to mention that I am facing no issues with Wi-Fi hotspot at all and I could use Wi-Fi hotspot to share my current Wi-Fi connection and to share my LTE connection (while Wi-Fi is off)

**Comment by ghost** [comment]
I would like to mention that https://github.com/GPUCode/device_nokia_NB1/commit/7ffd99fe49c30685b312742636bd20f9980885ab & https://github.com/GPUCode/device_nokia_NB1/commit/512267caab966d76b7ec57a67a753e47eddcad8a seem to improve Wi-Fi performance especially with regards to roaming. Even though it didn't fix this issue, I think it's better to keep it.

**Comment by raphaelthegreat** [comment]
Which modem are you using?

**Comment by ghost** [comment]
@GPUCode I'm using the latest modem from the 2020-10 full OTA. Would you like me to upload it?

**Comment by ghost** [comment]
It is `998_GEN_PACK-1.197731.2.215258.2`.

**Comment by raphaelthegreat** [comment]
No, I was wondering how hotspot works for you without that flag. Removing the flag requires A1N modem firmware

**Comment by raphaelthegreat** [comment]
So after removing it, you faced no issues with hotspot whatsoever?

**Comment by ghost** [comment]
No issues whatsoever, both 2.4G and 5G works flawlessly

**Comment by raphaelthegreat** [comment]
With password, correct?

**Comment by ghost** [comment]
Yes

**Comment by ghost** [comment]
> Removing the flag requires A1N modem firmware

What do you mean?

Edit: my modem.img is from the Nokia 8's last full OTA

**Comment by raphaelthegreat** [comment]
We had discovered that using A1N modem firmware fixed many issues including hotspot etc: https://github.com/radu-v/umbrella-mod/releases/tag/modem-wlan-fw-1 Well if it works on the new tree I will try disabling it

**Comment by ghost** [comment]
Does LineageOS have some ability to let you bundle modem.img with the OTA zip file? So people for sure use the modem.img that works?

**Comment by ghost** [comment]
Also I get a warning on boot up which says "There's an internal problem with your device", it seems like it's related to fingerprint not matching between system and vendor. Does it happen for you too or did I break something on my device?

**Comment by raphaelthegreat** [comment]
> Also I get a warning on boot up which says "There's an internal problem with your device", it seems like it's related to fingerprint not matching between system and vendor. Does it happen for you too or did I break something on my device?

That error appears when the kernel is mismatched with the android framework. Can you send boot log for me to see the error?

**Comment by ghost** [comment]
@GPUCode Would it happen if I used `next ` kernel tree instead of `dot11`?

**Comment by raphaelthegreat** [comment]
Firstly the kernel has no dot11 branch. Secondly Idk what will happen. The next branch is a dumping ground of commits which we verify and then cherry pick into the main branch. Currently the next branch contains the Q qcacld-3.0 driver which might work or might not. Testing it though is not a bad idea.

**Comment by ghost** [comment]
@GPUCode These are the logs to the leadup to the warning: https://0x0.st/-gZ6.gz

**Comment by ghost** [comment]
> Firstly the kernel has no dot11 branch. Secondly Idk what will happen. The next branch is a dumping ground of commits which we verify and then cherry pick into the main branch. Currently the next branch contains the Q qcacld-3.0 driver which might work or might not. Testing it though is not a bad idea.

Well the `next` has been working really well so far and I've always been using it because I've noticed most changes and fixes are going through it first. Maybe it was responsible for making it possible to remove `WIFI_AVOID_IFACE_RESET_MAC_CHANGE` line? I guess we have changed so much that there is no way of knowing which change fixed this.

**Comment by ghost** [comment]
Closing. Solved:  https://github.com/GPUCode/device_nokia_NB1/commit/20b141024761010bb65ec5928a53b9ab53b77b86
