### ISSUE TITLE
LOS recovery

### ISSUE THREAD

**Issue by ghost** [raphaelthegreat/device_nokia_NB1#5]
I'm not able to boot up LOS recovery and always find myself needing to install TWRP as well. I don't have any advanced needs so I would satisfied with just LOS recovery in most cases.

**Comment by raphaelthegreat** [comment]
The integrated recovery needs a patch to work

**Comment by ghost** [comment]
Any tips because I've no idea how to go about this. I've tried looking at other devices but no idea how to fix this

**Comment by raphaelthegreat** [comment]
Reverting this commit fixes recovery: https://github.com/LineageOS/android_bootable_recovery/commit/f65d48bb5ac611a9dbfba150cfdb0bfc5fd6aaf8#diff-d5b394a3c173828a7bbd773f4522beaeadc11d1c46b77f4d4b4086af332bef0d

**Comment by ghost** [comment]
@GPUCode How could I do this from a local_manifest? Do I have to maintain my own `android_bootable_recovery`?

**Comment by raphaelthegreat** [comment]
I just revert it in the source tree. If you want to clone it, you need to fork it apply the revert and clone your fork

**Comment by ghost** [comment]
Thanks, I'll try this now. Do other devices have this issue? Hopefully these things don't block it from ever becoming official.

**Comment by ghost** [comment]
> Reverting this commit fixes recovery: [LineageOS/android_bootable_recovery@f65d48b#diff-d5b394a3c173828a7bbd773f4522beaeadc11d1c46b77f4d4b4086af332bef0d](https://github.com/LineageOS/android_bootable_recovery/commit/f65d48bb5ac611a9dbfba150cfdb0bfc5fd6aaf8#diff-d5b394a3c173828a7bbd773f4522beaeadc11d1c46b77f4d4b4086af332bef0d)

Are you sure this fixes LOS recovery? Not sure if you showed me the wrong commit

**Comment by ghost** [comment]
I think I reverted the commit wrong. I'm trying again. Is https://github.com/c79/android_bootable_recovery/tree/lineage-18.1_c79 correct?

**Comment by ghost** [comment]
Some updates: it appears that reverting the patch does work now but the bootup takes over a minute and it can't reboot itself.

Also at boot it has the following error:

```
E: Failed to clear BCB message: failed to open /dev/block/bootdevice/by-name/misc: No such file or directory
E: Failed to clear BCB message: failed to open /dev/block/bootdevice/by-name/misc: No such file or directory
```

Edit: I have a feeling that it did work out the first time but I was impatient about waiting a minute

**Comment by ghost** [comment]
Some updates, I booted up into TWRP and it does appear that I do have a completely zero-ed out misc partition. TWRP does in fact show `/dev/block/bootdevice/by-name/misc`.... not sure why LOS says I don't have one :/

**Comment by ghost** [comment]
Any tips on how to solve this? I'm willing to test any patches you propose.

**Comment by raphaelthegreat** [comment]
I pushed this that might fix the misc issue: https://github.com/GPUCode/device_nokia_NB1/commit/13f97aae38335f83c7cc4828aacee85ec7b88818

**Comment by ghost** [comment]
I've added it to my dot11 branch, will let you know whether it fixes it: https://github.com/c79/device_nokia_NB1

**Comment by ghost** [comment]
```
[  4% 277/5790] Target buildinfo: out/target/product/NB1/obj/ETC/system_build_prop_intermediates/build.prop
Target buildinfo from: device/nokia/NB1/system.prop                                                                                                                    
[  4% 281/5790] Target vendor buildinfo: out/target/product/NB1/vendor/build.prop   
Target vendor properties from: device/nokia/NB1/vendor.prop               
[  5% 292/5790] build out/target/product/NB1/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows
FAILED: out/target/product/NB1/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows
/bin/bash -c "(ASAN_OPTIONS=detect_leaks=0 out/host/linux-x86/bin/checkpolicy -M -c             30 -o out/target/product/NB1/obj/FAKE/sepolicy_neverallows_intermediate
s/sepolicy_neverallows.tmp out/target/product/NB1/obj/FAKE/sepolicy_neverallows_intermediates/policy.conf ) && (out/host/linux-x86/bin/sepolicy-analyze out/target/prod
uct/NB1/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows.tmp neverallow -w -f out/target/product/NB1/obj/FAKE/sepolicy_neverallows_intermediates/policy
_2.conf ||        ( echo \"\" 1>&2;         echo \"sepolicy-analyze failed. This is most likely due to the use\" 1>&2;      echo \"of an expanded attribute in a nevera
llow assertion. Please fix\" 1>&2;          echo \"the policy.\" 1>&2;      exit 1 ) ) && (touch out/target/product/NB1/obj/FAKE/sepolicy_neverallows_intermediates/sep
olicy_neverallows.tmp ) && (mv out/target/product/NB1/obj/FAKE/sepolicy_neverallows_intermediates/sepolicy_neverallows.tmp out/target/product/NB1/obj/FAKE/sepolicy_nev
erallows_intermediates/sepolicy_neverallows )"
device/nokia/NB1/sepolicy/vendor/init.te:9:ERROR 'unknown type vendor_sysfs_graphics' at token ';' on line 97559:
allow init vendor_sysfs_graphics:dir search;
# Display
checkpolicy:  error(s) encountered while parsing configuration
[  5% 294/5790] build out/target/product/NB1/obj/ETC/sepolicy.recovery_intermediates/sepolicy
FAILED: out/target/product/NB1/obj/ETC/sepolicy.recovery_intermediates/sepolicy
/bin/bash -c "(ASAN_OPTIONS=detect_leaks=0 out/host/linux-x86/bin/checkpolicy -M -c             30 -o out/target/product/NB1/obj/ETC/sepolicy.recovery_intermediates/se
policy.tmp out/target/product/NB1/obj/ETC/sepolicy.recovery_intermediates/sepolicy.recovery.conf ) && (out/host/linux-x86/bin/sepolicy-analyze out/target/product/NB1/o
bj/ETC/sepolicy.recovery_intermediates/sepolicy.tmp permissive > out/target/product/NB1/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains ) && (if [ \
"userdebug\" = \"user\" -a -s out/target/product/NB1/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains ]; then                 echo \"==========\" 1>&
2;              echo \"ERROR: permissive domains not allowed in user builds\" 1>&2;             echo \"List of invalid domains:\" 1>&2;                 cat out/target/
product/NB1/obj/ETC/sepolicy.recovery_intermediates/sepolicy.permissivedomains 1>&2;            exit 1;                 fi ) && (mv out/target/product/NB1/obj/ETC/sepo
licy.recovery_intermediates/sepolicy.tmp out/target/product/NB1/obj/ETC/sepolicy.recovery_intermediates/sepolicy )"
device/nokia/NB1/sepolicy/vendor/init.te:9:ERROR 'unknown type vendor_sysfs_graphics' at token ';' on line 106534:
# Display
allow init vendor_sysfs_graphics:dir search;
checkpolicy:  error(s) encountered while parsing configuration
[  5% 295/5790] Building Kernel Config

```

Doesn't compile

**Comment by raphaelthegreat** [comment]
Revert this: 336fc2196e9fdedf708a4b2433c0aad95ccf5f81. This is only for the FPS info feature for HavocOS

**Comment by ghost** [comment]
Thanks, will do

**Comment by ghost** [comment]
No luck with the change, it doesn't appear to have helped. Same error.

**Comment by ghost** [comment]
Also USB doesn't seem to work properly in Lineage recovery. `Enable ADB` exists and when I select it it doesn't work and then just disappears. ADB Sideload is broken too 

Edit: might be connected to the misc partition error

**Comment by ghost** [comment]
Regarding the USB issue, it seems unrelated to misc error, /tmp/recovery.log says:

```
failed to open /sys/class/android_usb/android0/state: No such file or directory
614 616 usb_ffs.cpp:275] opening control endpoint /dev/usb-ffs/adb/ep0
614 616 usb_ffs.cpp:278] cannot open control endpoint /dev/usb-ffs/adb/ep0
```

**Comment by ghost** [comment]
It works now: https://github.com/c79/device_nokia_NB1/commit/53b282decb829242a88d1376ce17d183a3fffbc9 (except for USB)

Edit: never mind USB works fine

Edit2: it works fine but the issue now is that https://github.com/GPUCode/device_nokia_NB1/issues/7 is back 

Edit3: I thought I fixed the typo in fstab but it appears I have not. Trying again with the typo fixed: https://github.com/c79/device_nokia_NB1/commit/59830c14d97bb6eafd437ea189767f03a5c8d4b2

**Comment by ghost** [comment]
Well I don't think https://github.com/c79/device_nokia_NB1/commit/53b282decb829242a88d1376ce17d183a3fffbc9 and https://github.com/c79/device_nokia_NB1/commit/59830c14d97bb6eafd437ea189767f03a5c8d4b2 could cause #7 to occur again. Not sure what went wrong 

Edit: never mind: https://github.com/GPUCode/android_kernel_nokia_msm8998/commit/e9cc98a42ea31871897e889f667c57008edf1f52

**Comment by raphaelthegreat** [comment]
It seems that I need to revert this: https://github.com/GPUCode/device_nokia_NB1/commit/fca35120384582da4c2c754a47482269171e07bb and also partially cherry pick your commit.

**Comment by raphaelthegreat** [comment]
Btw thanks for all the help, finding and diagnosing issues with the device tree. If you want you can join our Telegram group, where we plan and discuss development for NB1 more in-depth: https://t.me/joinchat/KqmSokGGwCRmOTYy
