### ISSUE TITLE
This device has an internal problem

### ISSUE THREAD

**Issue by ghost** [raphaelthegreat/device_nokia_NB1#7]
Boot log: https://0x0.st/-gZ6.gz

I've tried to add the following to my `device.mk`:
```
# Verity
PRODUCT_SYSTEM_VERITY_PARTITION=/dev/block/bootdevice/by-name/system
PRODUCT_VENDOR_VERITY_PARTITION=/dev/block/bootdevice/by-name/vendor
$(call inherit-product, build/target/product/verity.mk)
```

but doesn't seem to fix it.

I am using TWRP and Magisk is installed via TWRP.

**Comment by raphaelthegreat** [comment]
It seems that removing module support from the kernel results in this:
`W VintfObject: VintfObject.verifyWithoutAvb() returns 1: Runtime info and framework compatibility matrix are incompatible: Missing config CONFIG_MODULES`

**Comment by ghost** [comment]
So this is an issue with https://github.com/GPUCode/android_kernel_nokia_msm8998 ?

**Comment by raphaelthegreat** [comment]
Yes
